### ISSUE TITLE
Support for YAML?

### ISSUE THREAD

**Issue by sebest** [Orange-OpenSource/angular-swagger-ui#13]
Hi,

Do you plan to add support for the yaml format?

thanx

**Comment by mathieuales** [comment]
Hi !
YAML support is not planned for now as i usually use JSON ...
Maybe you could do it as a module i could integrate ?
BR

**Comment by mathieuales** [comment]
Can be achieved in 0.2 by creating a module to parse yaml, see https://github.com/Orange-OpenSource/angular-swagger-ui#writing-your-own-modules
I won't do it as i don't need it :-(

**Comment by darosh** [comment]
Here is YAML parser module: [swagger-yaml.js](https://github.com/darosh/angular-swagger-ui-material/blob/master/src/modules/swagger-yaml.js) I just made, and it seems to be [working](http://darosh.github.io/angular-swagger-ui-material/#?url=https:%2F%2Fcdn.rawgit.com%2FAPIs-guru%2Fapi-models%2Fmaster%2FAPIs%2Fbbc.com%2F1.0.0%2Fswagger.yaml). It depends on: [nodeca/js-yaml](https://github.com/nodeca/js-yaml).

EDIT: it does not work for fom submit because `submitExplorer()` is using [var swagger](https://github.com/Orange-OpenSource/angular-swagger-ui/blob/d0bb9b93878bd77f6d9408022f2c13d042acc13e/src/scripts/swagger-ui.js#L194) which is set to [response data](https://github.com/Orange-OpenSource/angular-swagger-ui/blob/d0bb9b93878bd77f6d9408022f2c13d042acc13e/src/scripts/swagger-ui.js#L154) (which is YAML string) which could be convereted (here)[https://github.com/Orange-OpenSource/angular-swagger-ui/blob/d0bb9b93878bd77f6d9408022f2c13d042acc13e/src/scripts/swagger-ui.js#L157] but we cannot transform String to Object (using param reference) in `.execute(swaggerModules.BEFORE_PARSE, url, swagger)` .

EDIT: with added $http `transformResponse` in `BEFORE_LOAD` it should work [now](https://github.com/darosh/angular-swagger-ui-material/commit/efe30357af92a904ce5310e339daf1914bb8bcf1).
